In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/Hp/Downloads/sales_data.csv")

# Display first 5 rows
df.head()

,Order_ID,Order_Date,Customer,Product,Region,Quantity,Unit_Price,Sales
0,1001,2024-10-16,Customer_115,Laptop,East,4,29756,119024.0
1,1002,2023-05-23,Customer_755,Laptop,North,10,55802,558020.0
2,1003,2023-02-02,Customer_31,Laptop,South,4,66737,266948.0
3,1004,2024-09-08,Customer_28,Keyboard,South,9,55487,499383.0
4,1005,2023-08-14,Customer_460,Keyboard,East,1,21426,21426.0

In [2]:
df.shape

(10100, 8)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    10100 non-null  int64
 1   Order_Date  10100 non-null  object
 2   Customer    10100 non-null  object
 3   Product     10100 non-null  object
 4   Region      10100 non-null  object
 5   Quantity    10100 non-null  int64
 6   Unit_Price  10100 non-null  int64
 7   Sales       9998 non-null   float64
dtypes: float64(1), int64(3), object(4)
memory usage: 631.4+ KB

In [4]:
df.describe()

           Order_ID      Quantity    Unit_Price          Sales
count  10100.000000  10100.000000  10100.000000    9998.000000
mean    6001.731386      5.460396  40579.988317  222016.858572
std     2888.176722      2.868183  22992.326413  184328.379035
min     1001.000000      1.000000    511.000000     560.000000
25%     3494.750000      3.000000  20588.500000   68198.750000
50%     5999.500000      5.000000  40779.500000  170641.500000
75%     8507.250000      8.000000  60310.750000  333666.000000
max    11000.000000     10.000000  79999.000000  798880.000000

In [5]:
df.isnull().sum()

Order_ID        0
Order_Date      0
Customer        0
Product         0
Region          0
Quantity        0
Unit_Price      0
Sales         102
dtype: int64

In [6]:
df.duplicated().sum()

100

In [7]:
df["Sales"] = df["Sales"].fillna(df["Sales"].median())

In [8]:
df.isnull().sum()

Order_ID      0
Order_Date    0
Customer      0
Product       0
Region        0
Quantity      0
Unit_Price    0
Sales         0
dtype: int64

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

0

In [11]:
df["Customer"] = df["Customer"].str.strip().str.title()

In [12]:
df["Order_Date"].dtype

dtype('O')

In [13]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [14]:
df["Product"].unique()

array(['Laptop', 'Keyboard', 'Tablet', 'Monitor', 'Printer', 'Mobile',
       'Mouse'], dtype=object)

In [15]:
df["Region"].unique()

array(['East', 'North', 'South', 'West'], dtype=object)

In [16]:
df["Revenue"] = df["Quantity"] * df["Unit_Price"]

In [17]:
total_sales = df["Sales"].sum()

print("Total Sales:", total_sales)

Total Sales: 2213412652.0

In [18]:
average_sales = df["Sales"].mean()

print("Average Sales:", average_sales)

Average Sales: 221341.2652

In [19]:
total_quantity = df["Quantity"].sum()

print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 54587

In [20]:
region_sales = df.groupby("Region")["Sales"].sum()

region_sales

Region
East     579883872.0
North    562419042.5
South    522371652.0
West     548738085.5
Name: Sales, dtype: float64

In [21]:
product_sales = df.groupby("Product")["Sales"].sum()

product_sales

Product
Keyboard    315247763.0
Laptop      320853639.0
Mobile      318927816.5
Monitor     301989529.0
Mouse       330421414.5
Printer     313482051.0
Tablet      312490439.0
Name: Sales, dtype: float64

In [22]:
df["Month"] = df["Order_Date"].dt.month_name()
monthly_sales = df.groupby("Month")["Sales"].sum()

monthly_sales

Month
April        188463378.5
August       191162848.5
December     190113781.0
February     173194429.5
January      189576776.5
July         186142198.0
June         181345305.5
March        181116663.5
May          188662964.5
November     175641322.0
October      184521966.0
September    183471018.5
Name: Sales, dtype: float64